// OSRS Monster Database
// Complete monster data for slayer creatures
// Updated from OSRS Wiki: 2025-08-19

class MonsterDrop {
    constructor(id, name, members, quantity, noted, rarity, rolls) {
        this.id = id;
        this.name = name;
        this.members = members;
        this.quantity = quantity;
        this.noted = noted;
        this.rarity = rarity;
        this.rolls = rolls;
    }
}

class MonsterProperties {
    constructor(data) {
        this.id = data.id;
        this.name = data.name;
        this.combat_level = data.combat_level;
        this.hitpoints = data.hitpoints;
        this.max_hit = data.max_hit;
        this.attack_type = data.attack_type;
        this.attack_speed = data.attack_speed;
        this.aggressive = data.aggressive;
        this.poisonous = data.poisonous;
        this.venomous = data.venomous;
        this.immune_poison = data.immune_poison;
        this.immune_venom = data.immune_venom;
        this.weaknesses = data.weaknesses;
        this.slayer_monster = data.slayer_monster;
        this.slayer_level = data.slayer_level;
        this.slayer_xp = data.slayer_xp;
        this.slayer_masters = data.slayer_masters;
        this.duplicate = data.duplicate;
        this.examine = data.examine;
        this.wiki_name = data.wiki_name;
        this.wiki_url = data.wiki_url;
        this.attack_level = data.attack_level;
        this.strength_level = data.strength_level;
        this.defence_level = data.defence_level;
        this.magic_level = data.magic_level;
        this.ranged_level = data.ranged_level;
        this.attack_bonus = data.attack_bonus;
        this.strength_bonus = data.strength_bonus;
        this.attack_magic = data.attack_magic;
        this.magic_bonus = data.magic_bonus;
        this.attack_ranged = data.attack_ranged;
        this.ranged_bonus = data.ranged_bonus;
        this.defence_stab = data.defence_stab;
        this.defence_slash = data.defence_slash;
        this.defence_crush = data.defence_crush;
        this.defence_magic = data.defence_magic;
        this.defence_ranged = data.defence_ranged;
        this.drops = data.drops || [];
        this.locations = data.locations || [];
    }
}

// Monster Database
const MONSTER_DATABASE = {
    'crawling-hand': new MonsterProperties({
        id: 'crawling-hand',
        name: 'Crawling Hand',
        combat_level: 8,
        hitpoints: 13,
        max_hit: 1,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 5,
        slayer_xp: 13,
        slayer_masters: ["turael","spria","vannaka","chaeldar"],
        duplicate: false,
        examine: 'Eek, a severed hand!',
        wiki_name: 'Crawling Hand',
        wiki_url: 'https://oldschool.runescape.wiki/w/Crawling_Hand',
        attack_level: 1,
        strength_level: 1,
        defence_level: 1,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Slayer Tower"],
        drops: []
    }),

    'cave-bug': new MonsterProperties({
        id: 'cave-bug',
        name: 'Cave bug',
        combat_level: 6,
        hitpoints: 8,
        max_hit: 1,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 7,
        slayer_xp: 8,
        slayer_masters: ["turael","spria","vannaka"],
        duplicate: false,
        examine: 'Not a bug you\'d want in your software.',
        wiki_name: 'Cave bug',
        wiki_url: 'https://oldschool.runescape.wiki/w/Cave_bug',
        attack_level: 1,
        strength_level: 1,
        defence_level: 1,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Lumbridge Swamp Caves"],
        drops: []
    }),

    'cave-crawler': new MonsterProperties({
        id: 'cave-crawler',
        name: 'Cave crawler',
        combat_level: 23,
        hitpoints: 23,
        max_hit: 2,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 10,
        slayer_xp: 23,
        slayer_masters: ["turael","spria","vannaka","chaeldar"],
        duplicate: false,
        examine: 'A nasty crawling creature.',
        wiki_name: 'Cave crawler',
        wiki_url: 'https://oldschool.runescape.wiki/w/Cave_crawler',
        attack_level: 3,
        strength_level: 3,
        defence_level: 3,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'banshee': new MonsterProperties({
        id: 'banshee',
        name: 'Banshee',
        combat_level: 23,
        hitpoints: 22,
        max_hit: 2,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 15,
        slayer_xp: 22,
        slayer_masters: ["turael","spria","vannaka","chaeldar"],
        duplicate: false,
        examine: 'A nasty undead creature.',
        wiki_name: 'Banshee',
        wiki_url: 'https://oldschool.runescape.wiki/w/Banshee',
        attack_level: 3,
        strength_level: 3,
        defence_level: 3,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Slayer Tower"],
        drops: []
    }),

    'cave-slime': new MonsterProperties({
        id: 'cave-slime',
        name: 'Cave slime',
        combat_level: 23,
        hitpoints: 25,
        max_hit: 3,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 17,
        slayer_xp: 25,
        slayer_masters: ["turael","spria","vannaka","chaeldar"],
        duplicate: false,
        examine: 'Yuck!',
        wiki_name: 'Cave slime',
        wiki_url: 'https://oldschool.runescape.wiki/w/Cave_slime',
        attack_level: 3,
        strength_level: 3,
        defence_level: 3,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Lumbridge Swamp Caves"],
        drops: []
    }),

    'rockslug': new MonsterProperties({
        id: 'rockslug',
        name: 'Rockslug',
        combat_level: 29,
        hitpoints: 26,
        max_hit: 3,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 20,
        slayer_xp: 26,
        slayer_masters: ["turael","spria","vannaka","chaeldar"],
        duplicate: false,
        examine: 'Rock hard slug.',
        wiki_name: 'Rockslug',
        wiki_url: 'https://oldschool.runescape.wiki/w/Rockslug',
        attack_level: 9,
        strength_level: 9,
        defence_level: 9,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 0,
        defence_slash: 0,
        defence_crush: 0,
        defence_magic: 0,
        defence_ranged: 0,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'cockatrice': new MonsterProperties({
        id: 'cockatrice',
        name: 'Cockatrice',
        combat_level: 37,
        hitpoints: 35,
        max_hit: 4,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 25,
        slayer_xp: 35,
        slayer_masters: ["vannaka","chaeldar"],
        duplicate: false,
        examine: 'Half chicken, half dragon.',
        wiki_name: 'Cockatrice',
        wiki_url: 'https://oldschool.runescape.wiki/w/Cockatrice',
        attack_level: 17,
        strength_level: 17,
        defence_level: 17,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 7,
        defence_slash: 7,
        defence_crush: 7,
        defence_magic: 0,
        defence_ranged: 7,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'pyrefiend': new MonsterProperties({
        id: 'pyrefiend',
        name: 'Pyrefiend',
        combat_level: 43,
        hitpoints: 40,
        max_hit: 4,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 30,
        slayer_xp: 40,
        slayer_masters: ["vannaka","chaeldar"],
        duplicate: false,
        examine: 'A fiery creature.',
        wiki_name: 'Pyrefiend',
        wiki_url: 'https://oldschool.runescape.wiki/w/Pyrefiend',
        attack_level: 23,
        strength_level: 23,
        defence_level: 23,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 13,
        defence_slash: 13,
        defence_crush: 13,
        defence_magic: 3,
        defence_ranged: 13,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'basilisk': new MonsterProperties({
        id: 'basilisk',
        name: 'Basilisk',
        combat_level: 61,
        hitpoints: 75,
        max_hit: 5,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 40,
        slayer_xp: 75,
        slayer_masters: ["vannaka","chaeldar"],
        duplicate: false,
        examine: 'Its gaze turns people to stone.',
        wiki_name: 'Basilisk',
        wiki_url: 'https://oldschool.runescape.wiki/w/Basilisk',
        attack_level: 41,
        strength_level: 41,
        defence_level: 41,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 31,
        defence_slash: 31,
        defence_crush: 31,
        defence_magic: 21,
        defence_ranged: 31,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'infernal-mage': new MonsterProperties({
        id: 'infernal-mage',
        name: 'Infernal Mage',
        combat_level: 66,
        hitpoints: 65,
        max_hit: 11,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 45,
        slayer_xp: 65,
        slayer_masters: ["vannaka","chaeldar"],
        duplicate: false,
        examine: 'A mage of the infernal kind.',
        wiki_name: 'Infernal Mage',
        wiki_url: 'https://oldschool.runescape.wiki/w/Infernal_Mage',
        attack_level: 46,
        strength_level: 46,
        defence_level: 46,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 36,
        defence_slash: 36,
        defence_crush: 36,
        defence_magic: 26,
        defence_ranged: 36,
        locations: ["Slayer Tower"],
        drops: []
    }),

    'bloodveld': new MonsterProperties({
        id: 'bloodveld',
        name: 'Bloodveld',
        combat_level: 76,
        hitpoints: 76,
        max_hit: 5,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 50,
        slayer_xp: 76.5,
        slayer_masters: ["vannaka","chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'Eeek, what a horrible creature.',
        wiki_name: 'Bloodveld',
        wiki_url: 'https://oldschool.runescape.wiki/w/Bloodveld',
        attack_level: 56,
        strength_level: 56,
        defence_level: 56,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 46,
        defence_slash: 46,
        defence_crush: 46,
        defence_magic: 36,
        defence_ranged: 46,
        locations: ["Slayer Tower","Catacombs of Kourend"],
        drops: []
    }),

    'jellies': new MonsterProperties({
        id: 'jellies',
        name: 'Jelly',
        combat_level: 78,
        hitpoints: 75,
        max_hit: 5,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 52,
        slayer_xp: 75,
        slayer_masters: ["vannaka","chaeldar","konar","nieve"],
        duplicate: false,
        examine: 'It\'s all gooey.',
        wiki_name: 'Jelly',
        wiki_url: 'https://oldschool.runescape.wiki/w/Jelly',
        attack_level: 58,
        strength_level: 58,
        defence_level: 58,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 48,
        defence_slash: 48,
        defence_crush: 48,
        defence_magic: 38,
        defence_ranged: 48,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'turoth': new MonsterProperties({
        id: 'turoth',
        name: 'Turoth',
        combat_level: 83,
        hitpoints: 76,
        max_hit: 8,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 55,
        slayer_xp: 76,
        slayer_masters: ["vannaka","chaeldar","konar","nieve"],
        duplicate: false,
        examine: 'A terrifying creature.',
        wiki_name: 'Turoth',
        wiki_url: 'https://oldschool.runescape.wiki/w/Turoth',
        attack_level: 63,
        strength_level: 63,
        defence_level: 63,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 53,
        defence_slash: 53,
        defence_crush: 53,
        defence_magic: 43,
        defence_ranged: 53,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'aberrant-spectre': new MonsterProperties({
        id: 'aberrant-spectre',
        name: 'Aberrant spectre',
        combat_level: 96,
        hitpoints: 90,
        max_hit: 8,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 60,
        slayer_xp: 90,
        slayer_masters: ["vannaka","chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'A ghastly spectre.',
        wiki_name: 'Aberrant spectre',
        wiki_url: 'https://oldschool.runescape.wiki/w/Aberrant_spectre',
        attack_level: 76,
        strength_level: 76,
        defence_level: 76,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 66,
        defence_slash: 66,
        defence_crush: 66,
        defence_magic: 56,
        defence_ranged: 66,
        locations: ["Slayer Tower","Catacombs of Kourend"],
        drops: []
    }),

    'dust-devil': new MonsterProperties({
        id: 'dust-devil',
        name: 'Dust devil',
        combat_level: 93,
        hitpoints: 105,
        max_hit: 8,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 65,
        slayer_xp: 105,
        slayer_masters: ["vannaka","chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'A whirling cloud of sandy doom.',
        wiki_name: 'Dust devil',
        wiki_url: 'https://oldschool.runescape.wiki/w/Dust_devil',
        attack_level: 73,
        strength_level: 73,
        defence_level: 73,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 63,
        defence_slash: 63,
        defence_crush: 63,
        defence_magic: 53,
        defence_ranged: 63,
        locations: ["Smoke Dungeon","Catacombs of Kourend"],
        drops: []
    }),

    'kurask': new MonsterProperties({
        id: 'kurask',
        name: 'Kurask',
        combat_level: 106,
        hitpoints: 97,
        max_hit: 4,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 70,
        slayer_xp: 97,
        slayer_masters: ["chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'Yuck, it\'s covered in slime.',
        wiki_name: 'Kurask',
        wiki_url: 'https://oldschool.runescape.wiki/w/Kurask',
        attack_level: 86,
        strength_level: 86,
        defence_level: 86,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 76,
        defence_slash: 76,
        defence_crush: 76,
        defence_magic: 66,
        defence_ranged: 76,
        locations: ["Fremennik Slayer Dungeon"],
        drops: []
    }),

    'skeletal-wyvern': new MonsterProperties({
        id: 'skeletal-wyvern',
        name: 'Skeletal Wyvern',
        combat_level: 140,
        hitpoints: 210,
        max_hit: 13,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 72,
        slayer_xp: 210,
        slayer_masters: ["konar","nieve","duradel"],
        duplicate: false,
        examine: 'Reanimated remains of an ancient wyvern.',
        wiki_name: 'Skeletal Wyvern',
        wiki_url: 'https://oldschool.runescape.wiki/w/Skeletal_Wyvern',
        attack_level: 120,
        strength_level: 120,
        defence_level: 120,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 110,
        defence_slash: 110,
        defence_crush: 110,
        defence_magic: 100,
        defence_ranged: 110,
        locations: ["Asgarnian Ice Dungeon"],
        drops: []
    }),

    'gargoyle': new MonsterProperties({
        id: 'gargoyle',
        name: 'Gargoyle',
        combat_level: 111,
        hitpoints: 105,
        max_hit: 9,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 75,
        slayer_xp: 105,
        slayer_masters: ["chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'An ugly stone creature.',
        wiki_name: 'Gargoyle',
        wiki_url: 'https://oldschool.runescape.wiki/w/Gargoyle',
        attack_level: 91,
        strength_level: 91,
        defence_level: 91,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 81,
        defence_slash: 81,
        defence_crush: 81,
        defence_magic: 71,
        defence_ranged: 81,
        locations: ["Slayer Tower"],
        drops: []
    }),

    'nechryael': new MonsterProperties({
        id: 'nechryael',
        name: 'Nechryael',
        combat_level: 115,
        hitpoints: 105,
        max_hit: 7,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 80,
        slayer_xp: 105,
        slayer_masters: ["chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'Eeew, it\'s all slimy.',
        wiki_name: 'Nechryael',
        wiki_url: 'https://oldschool.runescape.wiki/w/Nechryael',
        attack_level: 95,
        strength_level: 95,
        defence_level: 95,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 85,
        defence_slash: 85,
        defence_crush: 85,
        defence_magic: 75,
        defence_ranged: 85,
        locations: ["Slayer Tower","Catacombs of Kourend"],
        drops: []
    }),

    'spiritual-mage': new MonsterProperties({
        id: 'spiritual-mage',
        name: 'Spiritual mage',
        combat_level: 121,
        hitpoints: 75,
        max_hit: 16,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 83,
        slayer_xp: 75,
        slayer_masters: ["konar","nieve","duradel"],
        duplicate: false,
        examine: 'A spiritual manifestation of Saradomin.',
        wiki_name: 'Spiritual mage',
        wiki_url: 'https://oldschool.runescape.wiki/w/Spiritual_mage',
        attack_level: 101,
        strength_level: 101,
        defence_level: 101,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 91,
        defence_slash: 91,
        defence_crush: 91,
        defence_magic: 81,
        defence_ranged: 91,
        locations: ["God Wars Dungeon"],
        drops: []
    }),

    'abyssal-demon': new MonsterProperties({
        id: 'abyssal-demon',
        name: 'Abyssal demon',
        combat_level: 124,
        hitpoints: 150,
        max_hit: 8,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 85,
        slayer_xp: 150,
        slayer_masters: ["vannaka","chaeldar","konar","nieve","duradel"],
        duplicate: false,
        examine: 'A denizen of the Abyss!',
        wiki_name: 'Abyssal demon',
        wiki_url: 'https://oldschool.runescape.wiki/w/Abyssal_demon',
        attack_level: 104,
        strength_level: 104,
        defence_level: 104,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 94,
        defence_slash: 94,
        defence_crush: 94,
        defence_magic: 84,
        defence_ranged: 94,
        locations: ["Slayer Tower","Catacombs of Kourend"],
        drops: []
    }),

    'cave-kraken': new MonsterProperties({
        id: 'cave-kraken',
        name: 'Cave kraken',
        combat_level: 127,
        hitpoints: 125,
        max_hit: 28,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 87,
        slayer_xp: 125,
        slayer_masters: ["konar","nieve","duradel"],
        duplicate: false,
        examine: 'It looks kind of squiggly.',
        wiki_name: 'Cave kraken',
        wiki_url: 'https://oldschool.runescape.wiki/w/Cave_kraken',
        attack_level: 107,
        strength_level: 107,
        defence_level: 107,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 97,
        defence_slash: 97,
        defence_crush: 97,
        defence_magic: 87,
        defence_ranged: 97,
        locations: ["Kraken Cove"],
        drops: []
    }),

    'dark-beast': new MonsterProperties({
        id: 'dark-beast',
        name: 'Dark beast',
        combat_level: 182,
        hitpoints: 220,
        max_hit: 15,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 90,
        slayer_xp: 220,
        slayer_masters: ["nieve","duradel"],
        duplicate: false,
        examine: 'A ferocious dark creature.',
        wiki_name: 'Dark beast',
        wiki_url: 'https://oldschool.runescape.wiki/w/Dark_beast',
        attack_level: 162,
        strength_level: 162,
        defence_level: 162,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 152,
        defence_slash: 152,
        defence_crush: 152,
        defence_magic: 142,
        defence_ranged: 152,
        locations: ["Temple of Light","Catacombs of Kourend"],
        drops: []
    }),

    'smoke-devil': new MonsterProperties({
        id: 'smoke-devil',
        name: 'Smoke devil',
        combat_level: 160,
        hitpoints: 185,
        max_hit: 8,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 93,
        slayer_xp: 185,
        slayer_masters: ["nieve","duradel"],
        duplicate: false,
        examine: 'A devil made of smoke.',
        wiki_name: 'Smoke devil',
        wiki_url: 'https://oldschool.runescape.wiki/w/Smoke_devil',
        attack_level: 140,
        strength_level: 140,
        defence_level: 140,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 130,
        defence_slash: 130,
        defence_crush: 130,
        defence_magic: 120,
        defence_ranged: 130,
        locations: ["Smoke Devil Dungeon"],
        drops: []
    }),

    'hydra': new MonsterProperties({
        id: 'hydra',
        name: 'Hydra',
        combat_level: 194,
        hitpoints: 420,
        max_hit: 17,
        attack_type: ["melee"],
        attack_speed: 4,
        aggressive: false,
        poisonous: false,
        venomous: false,
        immune_poison: false,
        immune_venom: false,
        weaknesses: 'Varies by monster',
        slayer_monster: true,
        slayer_level: 95,
        slayer_xp: 420,
        slayer_masters: ["konar"],
        duplicate: false,
        examine: 'A many-headed beast.',
        wiki_name: 'Hydra',
        wiki_url: 'https://oldschool.runescape.wiki/w/Hydra',
        attack_level: 174,
        strength_level: 174,
        defence_level: 174,
        magic_level: 1,
        ranged_level: 1,
        defence_stab: 164,
        defence_slash: 164,
        defence_crush: 164,
        defence_magic: 154,
        defence_ranged: 164,
        locations: ["Karuulm Slayer Dungeon"],
        drops: []
    }),

};

// Helper function to get all slayer monsters
function getSlayerMonsters() {
    return Object.values(MONSTER_DATABASE)
        .filter(monster => monster.slayer_monster && monster.slayer_level > 0)
        .sort((a, b) => a.slayer_level - b.slayer_level);
}

// Helper function to get monster by ID
function getMonsterById(id) {
    return MONSTER_DATABASE[id] || null;
}

// Helper function to format defense stats
function formatMonsterDefenses(monster) {
    return `Stab: ${monster.defence_stab}, Slash: ${monster.defence_slash}, Crush: ${monster.defence_crush}, Magic: ${monster.defence_magic}, Ranged: ${monster.defence_ranged}`;
}

// Helper function to format notable drops
function formatMonsterDrops(monster) {
    if (!monster.drops || monster.drops.length === 0) {
        return 'No notable drops';
    }
    
    // Get rare drops (rarity < 0.1)
    const rareDrops = monster.drops
        .filter(drop => drop.rarity < 0.1)
        .slice(0, 5)
        .map(drop => drop.name);
    
    if (rareDrops.length > 0) {
        return rareDrops.join(', ');
    }
    
    // If no rare drops, show common valuable drops
    return monster.drops
        .slice(0, 3)
        .map(drop => drop.name)
        .join(', ');
}

// Export for use in other files (if using modules)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        MONSTER_DATABASE,
        getSlayerMonsters,
        getMonsterById,
        formatMonsterDefenses,
        formatMonsterDrops
    };
}
